### ISSUE TITLE
Polymorphic change to Controller ConsumeCommand

### ISSUE THREAD

**Issue by ImpulseChimp** [ImpulseChimp/MarsRoverKata#13]
While a better design for the code, the benefit would be more code for a cleaner controller. If the rover was more complex with more types of commands, I would definitely do this since it would make everything better, but since the rover is so simple in this project, I will probably avoid setting this up for my current code base.

**Comment by cidthecoatrack** [comment]
@ImpulseChimp Fair enough.  It is certainly a discussion, mainly on MVP vs. extensibility.  Again, no wrong answer.
