### ISSUE TITLE
Naming grid folder plural

### ISSUE THREAD

**Issue by ImpulseChimp** [ImpulseChimp/MarsRoverKata#3]
It is best practice, when having solution folders, to name the folders plural. That way, you can avoid potential namespace conflicts - if you want "Grid", the system won't know if you mean the namespace Grid or the object Grid. So, rename the folder to "Grids", and you're safe.

Is it expecting a namespace for the folder name? Grid is in the MarsRoverKata namespace so would Grid/Grids ever be a conflict?

**Comment by cidthecoatrack** [comment]
@ImpulseChimp When you create solution folders, and then classes in that folder, it uses the folder to create namespaces.  So, if you have `{solution}/Grids` as a folder, and you create `{solution}/Grids/Grid.cs`, it would get the namespace `MarsRoverKata.Grids.Grid`.  The other side is when you MOVE a class into a folder, Visual Studio (if you see VS, that's what it means) isn't smart enough to update the namespace.  So, you have to manually change the namespace to be the plural form.  The get down to brass tacks, the folder-plural convention is actually a namespace-plural convention.

**Comment by ImpulseChimp** [comment]
@cidthecoatrack Oh gotcha. I assumed the namespace was god at a single level so multiple level namespaces explains that perfectly.
