### ISSUE TITLE
the "Active" boolean could become implicit

### ISSUE THREAD

**Issue by ImpulseChimp** [ImpulseChimp/MarsRoverKata#9]
I agree with this for readability, but this would also waste computation. The active property of the grid is checked during each command from the rover so to calculate if the active property seems a little excessive. With true or false decided on creation, it's calculated once and never touched again.

**Comment by cidthecoatrack** [comment]
Very true.  Another way you can do this is with a `readonly` property.  It would look like `public readonly Boolean Active`, which you can set in the constructor and be done.

**Comment by ImpulseChimp** [comment]
Making it a public readonly is perfect for this. I'm changing it to that right now.

**Comment by ImpulseChimp** [comment]
Changed and done.
